"""add post image

Revision ID: caabe4a750bf
Revises: 
Create Date: 2018-07-06 21:37:19.933640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caabe4a750bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=128), nullable=True),
    sa.Column('post_text', sa.String(length=1024), nullable=True),
    sa.Column('post_datetime', sa.DateTime(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('post_image_ref', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_post_datetime'), 'posts', ['post_datetime'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('reg_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('about_user', sa.String(length=140), nullable=True),
    sa.Column('userpic', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_reg_datetime'), 'users', ['reg_datetime'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_text', sa.String(length=256), nullable=True),
    sa.Column('comment_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_comment_datetime'), 'comments', ['comment_datetime'], unique=False)
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deck_name', sa.String(length=128), nullable=True),
    sa.Column('deck_info', sa.String(length=256), nullable=True),
    sa.Column('creation_datetime', sa.DateTime(), nullable=True),
    sa.Column('deckpic', sa.BLOB(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_creation_datetime'), 'decks', ['creation_datetime'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_name', sa.String(length=64), nullable=True),
    sa.Column('question', sa.String(length=1024), nullable=True),
    sa.Column('answer', sa.String(length=512), nullable=True),
    sa.Column('card_img1', sa.BLOB(), nullable=True),
    sa.Column('card_img2', sa.BLOB(), nullable=True),
    sa.Column('card_img3', sa.BLOB(), nullable=True),
    sa.Column('card_statistic', sa.String(length=32), nullable=True),
    sa.Column('deck_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    op.drop_index(op.f('ix_decks_creation_datetime'), table_name='decks')
    op.drop_table('decks')
    op.drop_index(op.f('ix_comments_comment_datetime'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_reg_datetime'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_posts_post_datetime'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
