"""add skills table

Revision ID: ee611766a455
Revises: caabe4a750bf
Create Date: 2018-07-10 21:56:17.020078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee611766a455'
down_revision = 'caabe4a750bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_skill', sa.String(length=128), nullable=True),
    sa.Column('second_skill', sa.String(length=128), nullable=True),
    sa.Column('third_skill', sa.String(length=128), nullable=True),
    sa.Column('fourth_skill', sa.String(length=128), nullable=True),
    sa.Column('fifth_skill', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###
